
setClass("MidCoords",
         slots = list(mid_x = "numeric",
                      mid_y = "numeric"),
         prototype = list(mid_x = NA_real_,
                          mid_y = NA_real_))

setClass("OuterCoords",
         slots = list(min_x = "numeric",
                      min_y = "numeric",
                      max_x = "numeric",
                      max_y = "numeric"),
         prototype = list(min_x = NA_real_,
                          min_y = NA_real_,
                          max_x = NA_real_,
                          max_y = NA_real_))

setClass("NeighbourCells",
         slots = list(top = "numeric",
                      right = "numeric",
                      bottom = "numeric",
                      left = "numeric",
                      top_right = "numeric",
                      bottom_right = "numeric",
                      bottom_left = "numeric",
                      top_left = "numeric"),
         prototype = list(top = NA_real_,
                          right = NA_real_,
                          bottom = NA_real_,
                          left = NA_real_,
                          top_right = NA_real_,
                          bottom_right = NA_real_,
                          bottom_left = NA_real_,
                          top_left = NA_real_))

setClass("CoarseCell",
         slots = list(id = "numeric",
                      mid_coords = "MidCoords",
                      outer_coords = "OuterCoords",
                      LC_deltas = "numeric",
                      neighbour_cells = "NeighbourCells",
                      cell_area = "numeric",
                      ref_cells = "data.frame",
                      sum_ref_cells = "numeric",
                      ref_cells_area = "numeric"),
         prototype = list(id = NA_real_,
                          mid_coords = new("MidCoords"),
                          outer_coords = new("OuterCoords"),
                          LC_deltas = NA_real_,
                          neighbour_cells = new("NeighbourCells"),
                          cell_area = NA_real_,
                          ref_cells = data.frame(),
                          sum_ref_cells = NA_real_,
                          ref_cells_area = NA_real_),
         contains = c("MidCoords",
                      "OuterCoords",
                      "NeighbourCells"))
