
setClass("CoarseCell",
         slots = list(cell_number = "numeric",
                      LC_deltas = "numeric",
                      neighbour_cells = "numeric",
                      cell_area = "numeric",
                      ref_cells = "SpatRaster",
                      kernel_densities = "SpatRaster",
                      agg_ref_cells = "numeric",
                      ref_cells_area = "numeric"),
         prototype = list(cell_number = NA_real_,
                          LC_deltas = NA_real_,
                          neighbour_cells = NA_real_,
                          cell_area = NA_real_,
                          ref_cells = rast(),
                          kernel_densities = rast(),
                          agg_ref_cells = NA_real_,
                          ref_cells_area = NA_real_))
